// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  name, email, age
) VALUES (
  $1, $2, $3
)
`

func (q *Queries) CreateUser(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser)
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, age FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Age,
	)
	return i, err
}

const updateUserAges = `-- name: UpdateUserAges :exec
UPDATE users SET age = $2
WHERE id = $1
`

func (q *Queries) UpdateUserAges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateUserAges)
	return err
}
